(function(){
    
    angular
        .module("IndexCardApp")
        .factory("dataService", dataFactory);
    
        function dataFactory(){
            var dataObj = {
                wordsData: wordsData   
            };
            return dataObj;
        }
            
    
        var wordsData = [
            
            {polishWord:"Komputer osobisty",englishWord:"personal computer",category:"IT",type:"text"},
            {polishWord:"pisać na klawiaturze",englishWord:"type",category:"IT",type:"text"},
            {polishWord:"ekran kineskopowy",englishWord:"crt screen",category:"IT",type:"text"},
            {polishWord:"pasek narzędzi",englishWord:"toolbar",category:"IT",type:"text"},
            {polishWord:"arkusz kalkulacyjny",englishWord:"spreadsheet",category:"IT",type:"text"},
            {polishWord:"baza danych",englishWord:"database",category:"IT",type:"text"},
            {polishWord:"głośnik ",englishWord:"speaker",category:"IT",type:"text"},
            {polishWord:"aparat cyfrowy",englishWord:"digital camera",category:"IT",type:"text"},
            {polishWord:"ekran ciekło krystaliczny",englishWord:"lcd screen",category:"IT",type:"text"},
            {polishWord:"pasek menu ",englishWord:"menu bar",category:"IT",type:"text"},
            {polishWord:"kolumna",englishWord:"column",category:"IT",type:"text"},
            {polishWord:"skomputeryzowany",englishWord:"computerized",category:"IT",type:"text"},
            {polishWord:"monitor",englishWord:"monitor",category:"IT",type:"text"},
            {polishWord:"skaner",englishWord:"scanner",category:"IT",type:"text"},
            {polishWord:"kolor podstawowy",englishWord:"primary color",category:"IT",type:"text"},
            {polishWord:"czcionka",englishWord:"font",category:"IT",type:"text"},
            {polishWord:"pionowy",englishWord:"vertical",category:"IT",type:"text"},
            {polishWord:"zapis, protokół, rejestr",englishWord:"record",category:"IT",type:"text"},
            {polishWord:"kamera internetowa",englishWord:"webcam",category:"IT",type:"text"},
            {polishWord:"mikrofon",englishWord:"microphone",category:"IT",type:"text"},
            {polishWord:"świecić, wydzielać blask, tlić się",englishWord:"glow",category:"IT",type:"text"},
            {polishWord:"cofnij",englishWord:"undo",category:"IT",type:"text"},
            {polishWord:"szereg",englishWord:"row",category:"IT",type:"text"},
            {polishWord:"rejestrować, zapisywać, przechowywać w rejestrze",englishWord:"keep a record",category:"IT",type:"text"},
            {polishWord:"oprogramowanie",englishWord:"software",category:"IT",type:"text"},
            {polishWord:"ekran dotykowy",englishWord:"touch screen",category:"IT",type:"text"},
            {polishWord:"mrugać, migotać",englishWord:"flicker",category:"IT",type:"text"},
            {polishWord:"wyrównanie tekstu",englishWord:"alignment",category:"IT",type:"text"},
            {polishWord:"poziomy",englishWord:"horizontal",category:"IT",type:"text"},
            {polishWord:"zbiór, kolekcja",englishWord:"collection",category:"IT",type:"text"},
            {polishWord:"edytor tekstu",englishWord:"word processor",category:"IT",type:"text"},
            {polishWord:"pióro świetlne",englishWord:"light pen",category:"IT",type:"text"},
            {polishWord:"wydzielać promieniowanie",englishWord:"emit radiation",category:"IT",type:"text"},
            {polishWord:"narzędzia graficzne",englishWord:"graphic tools",category:"IT",type:"text"},
            {polishWord:"cyfra, liczba, suma, kwota, rysunek, figura",englishWord:"figure",category:"IT",type:"text"},
            {polishWord:"pole (np. W bazie danych)",englishWord:"field",category:"IT",type:"text"},
            {polishWord:"napęd",englishWord:"drive",category:"IT",type:"text"},
            {polishWord:"czytnik kodów kreskowych",englishWord:"barcode reader",category:"IT",type:"text"},
            {polishWord:"aktywny",englishWord:"active",category:"IT",type:"text"},
            {polishWord:"narzędzia rysowania",englishWord:"drawing tools",category:"IT",type:"text"},
            {polishWord:"wypełniać np. Formularz",englishWord:"fill in",category:"IT",type:"text"},
            {polishWord:"Procesor w komputerze",englishWord:"central processing unit",category:"IT",type:"text"},
            {polishWord:"panel dotykowy",englishWord:"touchpad",category:"IT",type:"text"},
            {polishWord:"matryca",englishWord:"matrix",category:"IT",type:"text"},
            {polishWord:"nagłówek",englishWord:"header",category:"IT",type:"text"},
            {polishWord:"komurka (w tabeli lub biologiczna",englishWord:"cell",category:"IT",type:"text"},
            {polishWord:"formularz, forma",englishWord:"form",category:"IT",type:"text"},
            {polishWord:"modem",englishWord:"modem",category:"IT",type:"text"},
            {polishWord:"klawisze alfanumeryczne",englishWord:"alphanumeric keys",category:"IT",type:"text"},
            {polishWord:"tranzystor cienkowarstwowy",englishWord:"thin-film transistor",category:"IT",type:"text"},
            {polishWord:"cecha, funkcjonalność funkcja programu",englishWord:"feature",category:"IT",type:"text"},
            {polishWord:"formuła, wzór",englishWord:"formula",category:"IT",type:"text"},
            {polishWord:"typ",englishWord:"type",category:"IT",type:"text"},
            {polishWord:"myszka",englishWord:"mouse",category:"IT",type:"text"},
            {polishWord:"maszyna do pisania",englishWord:"type writter",category:"IT",type:"text"},
            {polishWord:"rozmiar obrazu (ekranu)",englishWord:"screen size",category:"IT",type:"text"},
            {polishWord:"napisać ponownie na maszynie lub komp",englishWord:"retype",category:"IT",type:"text"},
            {polishWord:"formuły, wzory",englishWord:"formulas",category:"IT",type:"text"},
            {polishWord:"notka",englishWord:"note",category:"IT",type:"text"},
            {polishWord:"klawiatura numeryczna",englishWord:"numeric keypad",category:"IT",type:"text"},
            {polishWord:"po przekątnej",englishWord:"diagonally",category:"IT",type:"text"},
            {polishWord:"literówka, błąd w druku",englishWord:"typo",category:"IT",type:"text"},
            {polishWord:"wejście",englishWord:"entry",category:"IT",type:"text"},
            {polishWord:"łączyc, linkować",englishWord:"link",category:"IT",type:"text"},
            {polishWord:"drukarka",englishWord:"printer",category:"IT",type:"text"},
            {polishWord:"klawisze edycji",englishWord:"editing keys",category:"IT",type:"text"},
            {polishWord:"cal",englishWord:"inch",category:"IT",type:"text"},
            {polishWord:"kasować, usuwać",englishWord:"delete",category:"IT",type:"text"},
            {polishWord:"obliczać, szacować, kalkulować",englishWord:"calculate",category:"IT",type:"text"},
            {polishWord:"osadzać, wstawiać, zagnieżdzać",englishWord:"embed",category:"IT",type:"text"},
            {polishWord:"część",englishWord:"part",category:"IT",type:"text"},
            {polishWord:"przełączać",englishWord:"switch",category:"IT",type:"text"},
            {polishWord:"rozdzielczość",englishWord:"resolution",category:"IT",type:"text"},
            {polishWord:"akapit, ustęp, paragraf",englishWord:"paragraph",category:"IT",type:"text"},
            {polishWord:"wartość, wielkość",englishWord:"value",category:"IT",type:"text"},
            {polishWord:"alternatywy",englishWord:"alternative",category:"IT",type:"text"},
            {polishWord:"przyjmować np. dane",englishWord:"accept",category:"IT",type:"text"},
            {polishWord:"klawisze funkcyjne",englishWord:"function keys",category:"IT",type:"text"},
            {polishWord:"jasność wyrazistość przejrzystość",englishWord:"clarity",category:"IT",type:"text"},
            {polishWord:"ślad, śledź (czas.)",englishWord:"trace",category:"IT",type:"text"},
            {polishWord:"równianie",englishWord:"equation",category:"IT",type:"text"},
            {polishWord:"hiperłącze",englishWord:"hiperlink",category:"IT",type:"text"},
            {polishWord:"Klawiatura",englishWord:"keyboard",category:"IT",type:"text"},
            {polishWord:"przetwarzać dane",englishWord:"process data",category:"IT",type:"text"},
            {polishWord:"klawisze strzałek",englishWord:"arrow keys",category:"IT",type:"text"},
            {polishWord:"piksel",englishWord:"pixel",category:"IT",type:"text"},
            {polishWord:"wklejać",englishWord:"paste",category:"IT",type:"text"},
            {polishWord:"suma",englishWord:"total",category:"IT",type:"text"},
            {polishWord:"indeks, spis, katalog",englishWord:"index",category:"IT",type:"text"},
            {polishWord:"przechowywać",englishWord:"store",category:"IT",type:"text"},
            {polishWord:"zamykać, blokować",englishWord:"lock",category:"IT",type:"text"},
            {polishWord:"poziomo",englishWord:"horizontal",category:"IT",type:"text"},
            {polishWord:"wstawiać, wprowadzać, umieścić ",englishWord:"insert",category:"IT",type:"text"},
            {polishWord:"procent, odsetek",englishWord:"percentage",category:"IT",type:"text"},
            {polishWord:"sortować, układać",englishWord:"sort",category:"IT",type:"text"},
            {polishWord:"wysyłać, przesyłać",englishWord:"output",category:"IT",type:"text"},
            {polishWord:"strona",englishWord:"page",category:"IT",type:"text"},
            {polishWord:"pionowo",englishWord:"vertical",category:"IT",type:"text"},
            {polishWord:"zamieniać, wymieniać, zastępować",englishWord:"replace",category:"IT",type:"text"},
            {polishWord:"zniżka, rabat",englishWord:"discount",category:"IT",type:"text"},
            {polishWord:"definiować",englishWord:"define",category:"IT",type:"text"},
            {polishWord:"sprzęt komputerowy, podzespoły",englishWord:"hardware",category:"IT",type:"text"},
            {polishWord:"klawisze dedykowane",englishWord:"dedicated keys",category:"IT",type:"text"},
            {polishWord:"ostrość",englishWord:"sharpness",category:"IT",type:"text"},
            {polishWord:"zawijanie tekstu",englishWord:"word wrap",category:"IT",type:"text"},
            {polishWord:"funkcja np. W programie lub kodzie",englishWord:"function",category:"IT",type:"text"},
            {polishWord:"relacyjny",englishWord:"relational",category:"IT",type:"text"},
            {polishWord:"zestaw, komplet",englishWord:"set",category:"IT",type:"text"},
            {polishWord:"komenda",englishWord:"command",category:"IT",type:"text"},
            {polishWord:"jasność",englishWord:"brightness",category:"IT",type:"text"},
            {polishWord:"dopasowywać, dostosowywać",englishWord:"adjust",category:"IT",type:"text"},
            {polishWord:"wykonywać np. polecenia w kodzie",englishWord:"carry out",category:"IT",type:"text"},
            {polishWord:"zapytanie np. do baz danych",englishWord:"query",category:"IT",type:"text"},
            {polishWord:"układ scalony",englishWord:"chip",category:"IT",type:"text"},
            {polishWord:"znak (w tekście)",englishWord:"charakter",category:"IT",type:"text"},
            {polishWord:"głębia koloru",englishWord:"colour depth",category:"IT",type:"text"},
            {polishWord:"margines",englishWord:"margin",category:"IT",type:"text"},
            {polishWord:"odnościć się, nawiązywać, mieć związek",englishWord:"refer",category:"IT",type:"text"},
            {polishWord:"jednocześnie",englishWord:"simultaneously",category:"IT",type:"text"},
            {polishWord:"jednostka, urządzenie",englishWord:"unit",category:"IT",type:"text"},
            {polishWord:"wyciąć, ciąć",englishWord:"cut",category:"IT",type:"text"},
            {polishWord:"częstotliwość odświerzania",englishWord:"refresh rate",category:"IT",type:"text"},
            {polishWord:"pogrubienie np. tekstu",englishWord:"bold",category:"IT",type:"text"},
            {polishWord:"pamięć operacyjna",englishWord:"random access memory",category:"IT",type:"text"},
            {polishWord:"wrócić, zwracać",englishWord:"return",category:"IT",type:"text"},
            {polishWord:"szeroki kąt widzenia",englishWord:"wide viewing angle",category:"IT",type:"text"},
            {polishWord:"grafika",englishWord:"graphics",category:"IT",type:"text"},
            {polishWord:"ramka, granica, kontur, brzeg",englishWord:"border",category:"IT",type:"text"},
            {polishWord:"rozwijać, opracowywać, projektować",englishWord:"develop",category:"IT",type:"text"},
            {polishWord:"pamięć tylko do odczytu",englishWord:"read-only memory",category:"IT",type:"text"},
            {polishWord:"spacja, odstęp, miejsce",englishWord:"space",category:"IT",type:"text"},
            {polishWord:"widok",englishWord:"view",category:"IT",type:"text"},
            {polishWord:"wykres",englishWord:"graph",category:"IT",type:"text"},
            {polishWord:"konwertować, przetwarzać",englishWord:"convert",category:"IT",type:"text"},
            {polishWord:"zarządzać",englishWord:"manage",category:"IT",type:"text"},
            {polishWord:"urządzenie peryferyjne, zewnętrzne",englishWord:"peripheral device",category:"IT",type:"text"},
            {polishWord:"wskaźnik myszy, kursor",englishWord:"pointer",category:"IT",type:"text"},
            {polishWord:"kąt",englishWord:"angle",category:"IT",type:"text"},
            {polishWord:"stopka",englishWord:"footer",category:"IT",type:"text"},
            {polishWord:"dyktować",englishWord:"dictate",category:"IT",type:"text"},
            {polishWord:"wspierać obsługiwać",englishWord:"support",category:"IT",type:"text"},
            {polishWord:"podłączony, podpięty, dołączony",englishWord:"attached",category:"IT",type:"text"},
            {polishWord:"przycisk",englishWord:"button",category:"IT",type:"text"},
            {polishWord:"wysokość",englishWord:"height",category:"IT",type:"text"},
            {polishWord:"układ graficzny",englishWord:"layout",category:"IT",type:"text"},
            {polishWord:"uruchamiać np. program",englishWord:"launch",category:"IT",type:"text"},
            {polishWord:"sieci",englishWord:"networks",category:"IT",type:"text"},
            {polishWord:"urządzenie wejściowe",englishWord:"input device",category:"IT",type:"text"},
            {polishWord:"przewijać",englishWord:"scroll",category:"IT",type:"text"},
            {polishWord:"szerokość",englishWord:"width",category:"IT",type:"text"},
            {polishWord:"wyciągać, wydobywać",englishWord:"extract",category:"IT",type:"text"},
            {polishWord:"czujnik",englishWord:"sensor",category:"IT",type:"text"},
            {polishWord:"łącznik, złączka, wtyczka",englishWord:"connector",category:"IT",type:"text"},
            {polishWord:"kliknąć dwukrotnie",englishWord:"double click",category:"IT",type:"text"},
            {polishWord:"modół sprawdzania pisowni",englishWord:"spell checker",category:"IT",type:"text"},
            {polishWord:"programista",englishWord:"programmer",category:"IT",type:"text"},
            {polishWord:"bezprzewodowy",englishWord:"wireless",category:"IT",type:"text"},
            {polishWord:"urządzenie pamięciowe, magazynujące",englishWord:"storage device",category:"IT",type:"text"},
            {polishWord:"dane wejściowe",englishWord:"input data",category:"IT",type:"text"},
            {polishWord:"podświetlać, wyróżniać, zakreślać",englishWord:"highlight",category:"IT",type:"text"},
            {polishWord:"specjalista wsparcia technicznego",englishWord:"support specialist",category:"IT",type:"text"},
            {polishWord:"przeciągać",englishWord:"drag",category:"IT",type:"text"},
            {polishWord:"stacja dysków",englishWord:"disc drive",category:"IT",type:"text"},
            {polishWord:"kabel",englishWord:"cable",category:"IT",type:"text"},
            {polishWord:"dane wyjściowe",englishWord:"output data",category:"IT",type:"text"},
            {polishWord:"rozpoznawać",englishWord:"recognize",category:"IT",type:"text"},
            {polishWord:"przytrzymać wciśnięty np.. Przycisk",englishWord:"hold down",category:"IT",type:"text"},
            {polishWord:"kierownik projektu",englishWord:"project manager",category:"IT",type:"text"},
            {polishWord:"port USB",englishWord:"USB port",category:"IT",type:"text"},
            {polishWord:"sygnał podczerwieni",englishWord:"infrared signal",category:"IT",type:"text"},
            {polishWord:"ekran",englishWord:"screen",category:"IT",type:"text"},
            {polishWord:"naciskać",englishWord:"press",category:"IT",type:"text"},
            {polishWord:"waluta",englishWord:"currency",category:"IT",type:"text"},
            {polishWord:"informatyka, prowadzenie obliczeń",englishWord:"computing",category:"IT",type:"text"},
            {polishWord:"pamięć główna",englishWord:"main memory",category:"IT",type:"text"},
            {polishWord:"wybrać, zaznaczyć",englishWord:"select",category:"IT",type:"text"},
            {polishWord:"zmęczenie",englishWord:"fatigue",category:"IT",type:"text"},
            {polishWord:"kursywa",englishWord:"italics",category:"IT",type:"text"},
            {polishWord:"dodawać, sumować",englishWord:"add",category:"IT",type:"text"},
            {polishWord:"analizować",englishWord:"analyse",category:"IT",type:"text"},
            {polishWord:"dane",englishWord:"data",category:"IT",type:"text"},
            {polishWord:"wielkie litery",englishWord:"capitals",category:"IT",type:"text"},
            {polishWord:"wyświetlacz plazmowy",englishWord:"plasma display",category:"IT",type:"text"},
            {polishWord:"podkreślenie np. tekstu",englishWord:"underlining",category:"IT",type:"text"},
            {polishWord:"zakres, przedział, zasięg",englishWord:"range",category:"IT",type:"text"},
            {polishWord:"projektować",englishWord:"design",category:"IT",type:"text"},
            {polishWord:"dostęp, dojście",englishWord:"access",category:"IT",type:"text"},
            {polishWord:"losowy",englishWord:"random",category:"IT",type:"text"},
            {polishWord:"urządzenie",englishWord:"device",category:"IT",type:"text"},
            {polishWord:"wcięcie, akapit",englishWord:"paragraph",category:"IT",type:"text"},
            {polishWord:"zapisywać",englishWord:"save",category:"IT",type:"text"},
            {polishWord:"etap, stadium, scena",englishWord:"stage",category:"IT",type:"text"},
            {polishWord:"poziom, etap",englishWord:"level",category:"IT",type:"text"},
            {polishWord:"kółko, koło",englishWord:"wheel",category:"IT",type:"text"},
            {polishWord:"długość",englishWord:"length",category:"IT",type:"text"},
            {polishWord:"wpisywać dane, wprowadzać dane",englishWord:"enter data",category:"IT",type:"text"},
            {polishWord:"scalić, połączyć",englishWord:"merge",category:"IT",type:"text"},
            {polishWord:"drukować",englishWord:"print",category:"IT",type:"text"},
            {polishWord:"projekt",englishWord:"project",category:"IT",type:"text"},
            {polishWord:"urządzenie wyjściowe",englishWord:"output device",category:"IT",type:"text"},
            {polishWord:"mysz optyczna",englishWord:"optical mouse",category:"IT",type:"text"},
            {polishWord:"liczba całkowita",englishWord:"integer",category:"IT",type:"text"},
            {polishWord:"plik",englishWord:"file",category:"IT",type:"text"},
            {polishWord:"szukać, poszukiwać",englishWord:"search",category:"IT",type:"text"},
            {polishWord:"analityk",englishWord:"analyst",category:"IT",type:"text"},
            {polishWord:"kliknąć PPM",englishWord:"right click",category:"IT",type:"text"},
            {polishWord:"badania i rozwój",englishWord:"research and development",category:"IT",type:"text"},
            {polishWord:"podłączyć",englishWord:"plug",category:"IT",type:"text"},
            {polishWord:"fala radiowa",englishWord:"radio wave",category:"IT",type:"text"},
            {polishWord:"system rozpoznawania mowy",englishWord:"voice-recognition system",category:"IT",type:"text"},
            {polishWord:"puszczać, upuszczać",englishWord:"relase",category:"IT",type:"text"},
            {polishWord:"wyświetlać",englishWord:"display",category:"IT",type:"text"},
            {polishWord:"wymagania",englishWord:"requirements",category:"IT",type:"text"},
            {polishWord:"załącznik",englishWord:"attachment",category:"IT",type:"text"},
            {polishWord:"strona internetowa",englishWord:"website",category:"IT",type:"text"},
            {polishWord:"bezpieczeństwo",englishWord:"security",category:"IT",type:"text"},
            {polishWord:"handel internetowy",englishWord:"e-commarce",category:"IT",type:"text"},
            {polishWord:"zdecentralizowany",englishWord:"decentralised",category:"IT",type:"text"},
            {polishWord:"polecać",englishWord:"recommend",category:"IT",type:"text"},
            {polishWord:"poczta tradycyjna, ślimacza",englishWord:"snail mail",category:"IT",type:"text"},
            {polishWord:"przeglądarka",englishWord:"browser",category:"IT",type:"text"},
            {polishWord:"oszustwo",englishWord:"fraud",category:"IT",type:"text"},
            {polishWord:"sklep internetowy",englishWord:"online shop",category:"IT",type:"text"},
            {polishWord:"cyfrowy",englishWord:"digital",category:"IT",type:"text"},
            {polishWord:"spełniac, dogadzać, wychodzić naprzeciw",englishWord:"cater for",category:"IT",type:"text"},
            {polishWord:"skrzynka pocztowa",englishWord:"mailbox",category:"IT",type:"text"},
            {polishWord:"interaktywny",englishWord:"interactive",category:"IT",type:"text"},
            {polishWord:"własność intelektualna",englishWord:"intellectual property",category:"IT",type:"text"},
            {polishWord:"zamawiać",englishWord:"order",category:"IT",type:"text"},
            {polishWord:"waluta",englishWord:"currency",category:"IT",type:"text"},
            {polishWord:"projektant stron internetowych",englishWord:"web designer",category:"IT",type:"text"},
            {polishWord:"adres skrzynki pocztowej",englishWord:"e-mail adress",category:"IT",type:"text"},
            {polishWord:"serfować po sieci",englishWord:"surf the web",category:"IT",type:"text"},
            {polishWord:"kradzież",englishWord:"theft",category:"IT",type:"text"},
            {polishWord:"dostarczać",englishWord:"deliver",category:"IT",type:"text"},
            {polishWord:"w porównaniu z",englishWord:"compared to",category:"IT",type:"text"},
            {polishWord:"inżynier oprogramowania",englishWord:"software engineer",category:"IT",type:"text"},
            {polishWord:"hasło",englishWord:"password",category:"IT",type:"text"},
            {polishWord:"protokół",englishWord:"protocol",category:"IT",type:"text"},
            {polishWord:"internetowe wyłudzanie",englishWord:"phishing",category:"IT",type:"text"},
            {polishWord:"wózek na zakupy",englishWord:"shoppin trolley",category:"IT",type:"text"},
            {polishWord:"zaleta, przewaga",englishWord:"advantage",category:"IT",type:"text"},
            {polishWord:"specjalista ds.. Zabezpieczeń",englishWord:"security specialist",category:"IT",type:"text"},
            {polishWord:"dostawca usług internetowych",englishWord:"internet service provider",category:"IT",type:"text"},
            {polishWord:"ścieżka np. ścieżka dostępu",englishWord:"path",category:"IT",type:"text"},
            {polishWord:"anonimowość",englishWord:"anonymity",category:"IT",type:"text"},
            {polishWord:"Certyfikat SSL",englishWord:"secure socket layer certificate",category:"IT",type:"text"},
            {polishWord:"administrator sieci informatycznej",englishWord:"network administrator",category:"IT",type:"text"},
            {polishWord:"przesyłać",englishWord:"transfer",category:"IT",type:"text"},
            {polishWord:"nazwa użytkownika",englishWord:"user name",category:"IT",type:"text"},
            {polishWord:"zakładka (np. W przeglądarce)",englishWord:"tab",category:"IT",type:"text"},
            {polishWord:"nadużycie, znęcanie się, maltret.",englishWord:"abuse",category:"IT",type:"text"},
            {polishWord:"kłódka",englishWord:"padlock",category:"IT",type:"text"},
            {polishWord:"bezpośrednio",englishWord:"directly",category:"IT",type:"text"},
            {polishWord:"instalować",englishWord:"install",category:"IT",type:"text"},
            {polishWord:"domena",englishWord:"domain",category:"IT",type:"text"},
            {polishWord:"ulubione",englishWord:"favourites",category:"IT",type:"text"},
            {polishWord:"nękanie w sieci",englishWord:"online harassment",category:"IT",type:"text"},
            {polishWord:"płatność",englishWord:"payment",category:"IT",type:"text"},
            {polishWord:"utrzymywać, zachowywać, konserwować",englishWord:"maintaint",category:"IT",type:"text"},
            {polishWord:"sieć",englishWord:"net",category:"IT",type:"text"},
            {polishWord:"DW (do wiadomości)",englishWord:"cc",category:"IT",type:"text"},
            {polishWord:"wyszukiwarka",englishWord:"search engine",category:"IT",type:"text"},
            {polishWord:"piractwo",englishWord:"piracy",category:"IT",type:"text"},
            {polishWord:"bramka płatnica",englishWord:"payment getaway",category:"IT",type:"text"},
            {polishWord:"izba rozliczeniowa",englishWord:"clearing house",category:"IT",type:"text"},
            {polishWord:"administrator baz danych",englishWord:"database administrator",category:"IT",type:"text"},
            {polishWord:"UDW",englishWord:"bcc",category:"IT",type:"text"},
            {polishWord:"strona domowa, startowa",englishWord:"homepage",category:"IT",type:"text"},
            {polishWord:"chroniony prawami autorskimi",englishWord:"copyright",category:"IT",type:"text"},
            {polishWord:"opłata",englishWord:"fee",category:"IT",type:"text"},
            {polishWord:"dokładność",englishWord:"accuracy",category:"IT",type:"text"},
            {polishWord:"temat",englishWord:"subject",category:"IT",type:"text"},
            {polishWord:"korzystać z internetu",englishWord:"use the internet",category:"IT",type:"text"},
            {polishWord:"złośliwe szkodliwe oprogramowanie",englishWord:"maleware",category:"IT",type:"text"},
            {polishWord:"porównywarka cenowa",englishWord:"pirice compression engine",category:"IT",type:"text"},
            {polishWord:"okazja, przecena",englishWord:"bargain",category:"IT",type:"text"},
            {polishWord:"konto",englishWord:"account",category:"IT",type:"text"},
            {polishWord:"wydajność",englishWord:"effaciency",category:"IT",type:"text"},
            {polishWord:"treść np. dokumentu",englishWord:"body",category:"IT",type:"text"},
            {polishWord:"zakupy przez internet",englishWord:"online shopping",category:"IT",type:"text"},
            {polishWord:"wirus",englishWord:"virus",category:"IT",type:"text"},
            {polishWord:"koszyk na zakupy",englishWord:"shopping basket",category:"IT",type:"text"},
            {polishWord:"zamrożony",englishWord:"frozen",category:"IT",type:"text"},
            {polishWord:"operator komputerowy",englishWord:"computer operator",category:"IT",type:"text"},
            {polishWord:"podpis, sygnatura",englishWord:"signature",category:"IT",type:"text"},
            {polishWord:"słowo kluczowe",englishWord:"keyword",category:"IT",type:"text"},
            {polishWord:"zainfekować",englishWord:"infect",category:"IT",type:"text"},
            {polishWord:"kasa w supermarkecie",englishWord:"checkout",category:"IT",type:"text"},
            {polishWord:"warunek konieczny, wymóg",englishWord:"perequisite",category:"IT",type:"text"},
            {polishWord:"uśmieszek np.. W mailu",englishWord:"smiley",category:"IT",type:"text"},
            {polishWord:"dział wsparcia technicznego",englishWord:"help desk",category:"IT",type:"text"},
            {polishWord:"finanse",englishWord:"finance",category:"IT",type:"text"},
            {polishWord:"mnożyć się, szerzyć się,",englishWord:"propagate",category:"IT",type:"text"},
            {polishWord:"karta kredytowa",englishWord:"credit card",category:"IT",type:"text"},
            {polishWord:"arbitralny",englishWord:"arbitrary",category:"IT",type:"text"},
            {polishWord:"rozwiązywanie problemów",englishWord:"troubleshooting",category:"IT",type:"text"},
            {polishWord:"emotikona, emotka",englishWord:"emoticon",category:"IT",type:"text"},
            {polishWord:"działalność wydawnicza, wydawanie",englishWord:"publishing",category:"IT",type:"text"},
            {polishWord:"plik wykonywalny",englishWord:"executable file",category:"IT",type:"text"},
            {polishWord:"karta debetowa",englishWord:"debit card",category:"IT",type:"text"},
            {polishWord:"limit, ograniczenia",englishWord:"limit",category:"IT",type:"text"},
            {polishWord:"rozwiązanie",englishWord:"solution",category:"IT",type:"text"},
            {polishWord:"lista mailingowa",englishWord:"mailing list",category:"IT",type:"text"},
            {polishWord:"dostęp",englishWord:"access",category:"IT",type:"text"},
            {polishWord:"wykorzystywać, wyzyskiwać",englishWord:"exploit",category:"IT",type:"text"},
            {polishWord:"portfel cyfrowy",englishWord:"digital wallet",category:"IT",type:"text"},
            {polishWord:"giełda walutowa",englishWord:"currency exchange",category:"IT",type:"text"},
            {polishWord:"praca zdalna",englishWord:"telework",category:"IT",type:"text"},
            {polishWord:"odbiorca",englishWord:"recipient",category:"IT",type:"text"},
            {polishWord:"globalny rynek",englishWord:"global market",category:"IT",type:"text"},
            {polishWord:"luka w zabezpieczeniach",englishWord:"secutiry flaw",category:"IT",type:"text"},
            {polishWord:"firma internetowa",englishWord:"dot-com",category:"IT",type:"text"},
            {polishWord:"portfel  ",englishWord:"wallet",category:"IT",type:"text"},
            {polishWord:"nauczanie z wykorzystaniem internetu",englishWord:"e-learning",category:"IT",type:"text"},
            {polishWord:"nadawca",englishWord:"sender",category:"IT",type:"text"},
            {polishWord:"rozkwitać ",englishWord:"flourish",category:"IT",type:"text"},
            {polishWord:"koń trojański",englishWord:"trojan horse",category:"IT",type:"text"},
            {polishWord:"nabywać, kupować",englishWord:"purchase",category:"IT",type:"text"},
            {polishWord:"sklep fizyczny i internetowy w jednym miejscu",englishWord:"brick and click",category:"IT",type:"text"},
            {polishWord:"biznes, interes, firma",englishWord:"business",category:"IT",type:"text"},
            {polishWord:"osoba zamieszczająca treści na stronie internetowej",englishWord:"content publisher",category:"IT",type:"text"},
            {polishWord:"zapisać się do np. listy mailingowej",englishWord:"subscribe",category:"IT",type:"text"},
            {polishWord:"przebrany, zakamuflowany",englishWord:"disguised",category:"IT",type:"text"},
            {polishWord:"program antywirusowy",englishWord:"antivirus program",category:"IT",type:"text"},
            {polishWord:"zabezpieczony",englishWord:"secured",category:"IT",type:"text"},
            {polishWord:"weryfikować",englishWord:"verify",category:"IT",type:"text"},
            {polishWord:"wypisać się",englishWord:"unsubscribe",category:"IT",type:"text"},
            {polishWord:"minimalizować",englishWord:"minimise",category:"IT",type:"text"},
            {polishWord:"ukrytee wejście, tylne wejście, furtka",englishWord:"backdoor",category:"IT",type:"text"},
            {polishWord:"zapora",englishWord:"firewall",category:"IT",type:"text"},
            {polishWord:"górnik",englishWord:"miner",category:"IT",type:"text"},
            {polishWord:"transakcja",englishWord:"transaction",category:"IT",type:"text"},
            {polishWord:"przesylać dalej",englishWord:"forward",category:"IT",type:"text"},
            {polishWord:"oprogramowanie szpiegujące",englishWord:"spyware",category:"IT",type:"text"},
            {polishWord:"darmowe oprogramowanie",englishWord:"freeware",category:"IT",type:"text"},
            {polishWord:"wynagradzanie, nagroda",englishWord:"reward",category:"IT",type:"text"},
            {polishWord:"ustawiać, ustanawiać, konfigurować, organizować",englishWord:"set up",category:"IT",type:"text"},
            {polishWord:"zapisywać, rejestrować, nagyrwać",englishWord:"record",category:"IT",type:"text"},
            {polishWord:"namierzyć, wyśledzić",englishWord:"track",category:"IT",type:"text"},
            {polishWord:"opóźnienie, zwłoka",englishWord:"delay",category:"IT",type:"text"},
            {polishWord:"obciążenie zwrotne, zwrot opłaty konpensata",englishWord:"chargeback",category:"IT",type:"text"},
            {polishWord:"fałszywy, podrobiony",englishWord:"fake",category:"IT",type:"text"},
            {polishWord:"oprogramowanie rozpowszechniane bez opłat",englishWord:"shareware",category:"IT",type:"text"},
            {polishWord:"generować",englishWord:"generate",category:"IT",type:"text"},
            {polishWord:"przejrzysty, przezroczysty",englishWord:"transparent",category:"IT",type:"text"},
            {polishWord:"kod",englishWord:"code",category:"IT",type:"text"},
            {polishWord:"przeglądać, oceniać",englishWord:"review",category:"IT",type:"text"},
            {polishWord:"innowacja",englishWord:"innovation",category:"IT",type:"text"},
            {polishWord:"platforma",englishWord:"platform",category:"IT",type:"text"},
            {polishWord:"księga główna, rejestr",englishWord:"ledger",category:"IT",type:"text"},
            {polishWord:"publiczny",englishWord:"public",category:"IT",type:"text"},
            {polishWord:"gniazdo, gniazdo elektryczne",englishWord:"socket",category:"IT",type:"text"},
            {polishWord:"warstwa, podkład",englishWord:"layer",category:"IT",type:"text"},
            {polishWord:"nawias klamrowy",englishWord:"braces",category:"IT",type:"text"},
            {polishWord:"właściwości",englishWord:"properties",category:"IT",type:"text"},
            {polishWord:"cecha",englishWord:"feature",category:"IT",type:"text"},
            {polishWord:"dodać ",englishWord:"add",category:"IT",type:"text"},
            {polishWord:"korzyść",englishWord:"benefit",category:"IT",type:"text"},
            {polishWord:"losowy",englishWord:"random",category:"IT",type:"text"},
            {polishWord:"karta dźwiękowa, muzyczna",englishWord:"soundcard",category:"IT",type:"text"},
            {polishWord:"awaria systemu komputerowego",englishWord:"computer crash",category:"IT",type:"text"},
            {polishWord:"bezprzewodowy",englishWord:"wireless",category:"IT",type:"text"},
            {polishWord:"błąd programu",englishWord:"error",category:"IT",type:"text"},
            {polishWord:"cyfrowy",englishWord:"digital",category:"IT",type:"text"},
            {polishWord:"dostęp do internetu",englishWord:"internet acces",category:"IT",type:"text"},
            {polishWord:"karta graficzna",englishWord:"graphic card",category:"IT",type:"text"},
            {polishWord:"katalog / folder",englishWord:"directory",category:"IT",type:"text"},
            {polishWord:"klawisz",englishWord:"key",category:"IT",type:"text"},
            {polishWord:"klawiatura",englishWord:"keybord",category:"IT",type:"text"},
            {polishWord:"kombatybilny",englishWord:"compatible",category:"IT",type:"text"},
            {polishWord:"komputer główny",englishWord:"host computer",category:"IT",type:"text"},
            {polishWord:"komputer osobisty",englishWord:"personal computer",category:"IT",type:"text"},
            {polishWord:"komputer stacjonarny",englishWord:"desktop computer",category:"IT",type:"text"},
            {polishWord:"konto",englishWord:"account",category:"IT",type:"text"},
            {polishWord:"kopia zapasowa",englishWord:"buck-up copy",category:"IT",type:"text"},
            {polishWord:"nagrywarka",englishWord:"recorder",category:"IT",type:"text"},
            {polishWord:"miniaturowy, kieszonkowy komputer",englishWord:"palmtop",category:"IT",type:"text"},
            {polishWord:"monitor komputerowy",englishWord:"computer display unit",category:"IT",type:"text"},
            {polishWord:"najczęściej zadawane pytania",englishWord:"frequently asked questions",category:"IT",type:"text"},
            {polishWord:"programista",englishWord:"programmer",category:"IT",type:"text"},
            {polishWord:"procesor",englishWord:"Central processing unit",category:"IT",type:"text"},
            {polishWord:"programowanie",englishWord:"programming",category:"IT",type:"text"},
            {polishWord:"program antywirusowy",englishWord:"anti-virus software",category:"IT",type:"text"},
            {polishWord:"projektowanie komputerowe",englishWord:"computer-aided design",category:"IT",type:"text"},
            {polishWord:"przeglądarka",englishWord:"browser",category:"IT",type:"text"},
            {polishWord:"pseudonim",englishWord:"nick",category:"IT",type:"text"},
            {polishWord:"pulpit",englishWord:"desktop",category:"IT",type:"text"},
            {polishWord:"rzecywistość wirtualna",englishWord:"virtual reality",category:"IT",type:"text"},
            {polishWord:"stacja dyskietek",englishWord:"floppy disc drive",category:"IT",type:"text"},
            {polishWord:"drukarka atramentowa",englishWord:"ink-jet printer",category:"IT",type:"text"},
            {polishWord:"drukarka igłowa",englishWord:"dot-matrix printer",category:"IT",type:"text"},
            {polishWord:"drukarka laserowa",englishWord:"laser printer",category:"IT",type:"text"},
            {polishWord:"dyskietka",englishWord:"floppy disc",category:"IT",type:"text"},
            {polishWord:"haker",englishWord:"hacker",category:"IT",type:"text"},
            {polishWord:"ikona",englishWord:"icon",category:"IT",type:"text"},
            {polishWord:"informatyka",englishWord:"computer science",category:"IT",type:"text"},
            {polishWord:"język programowania",englishWord:"programming lenguage",category:"IT",type:"text"},
            {polishWord:"interfejs",englishWord:"interface",category:"IT",type:"text"},
            {polishWord:"niepołoączony",englishWord:"offline",category:"IT",type:"text"},
            {polishWord:"połączony",englishWord:"online",category:"IT",type:"text"},
            {polishWord:"nośnik danych",englishWord:"data carrier",category:"IT",type:"text"},
            {polishWord:"obudowa",englishWord:"case",category:"IT",type:"text"},
            {polishWord:"pamięć",englishWord:"memory",category:"IT",type:"text"},
            {polishWord:"połoączenie internetowe",englishWord:"internet connection",category:"IT",type:"text"},
            {polishWord:"potwierdzenie",englishWord:"acknowledgement",category:"IT",type:"text"},
            {polishWord:"strona",englishWord:"site",category:"IT",type:"text"},
            {polishWord:"strona internetowa",englishWord:"website",category:"IT",type:"text"},
            {polishWord:"system operacyjny",englishWord:"operating system",category:"IT",type:"text"},
            {polishWord:"system operacyjny",englishWord:"operating system",category:"IT",type:"text"},
            {polishWord:"tapeta",englishWord:"wallpaper",category:"IT",type:"text"},
            {polishWord:"uaktualnienie",englishWord:"update",category:"IT",type:"text"},
            {polishWord:"ustawienia",englishWord:"settings",category:"IT",type:"text"},
            {polishWord:"wersja demo programu",englishWord:"demo version",category:"IT",type:"text"},
            {polishWord:"wlaściwości",englishWord:"properties",category:"IT",type:"text"},
            {polishWord:"wyście",englishWord:"exit",category:"IT",type:"text"},
            {polishWord:"zabezpieczenie",englishWord:"security",category:"IT",type:"text"},
            {polishWord:"załącznik",englishWord:"attachment",category:"IT",type:"text"},
            {polishWord:"zapytanie",englishWord:"enquiry",category:"IT",type:"text"},
            {polishWord:"podkładka pod mysz",englishWord:"mousepad",category:"IT",type:"text"},
            {polishWord:"kwestia",englishWord:"issue",category:"IT",type:"text"},
            {polishWord:"składnia",englishWord:"syntax",category:"IT",type:"text"},
            {polishWord:"pakiet",englishWord:"package",category:"IT",type:"text"},
            {polishWord:"odpowiedni",englishWord:"corresponding",category:"IT",type:"text"},
            {polishWord:"komunikat",englishWord:"statement",category:"IT",type:"text"},
            {polishWord:"różnorodny",englishWord:"various",category:"IT",type:"text"},
            {polishWord:"żarówka",englishWord:"bulb",category:"IT",type:"text"},
            {polishWord:"wskazać",englishWord:"indicate",category:"IT",type:"text"},
            {polishWord:"wykonać",englishWord:"perform",category:"IT",type:"text"},
            {polishWord:"zgięcie, wałeczek fałda",englishWord:"fold",category:"IT",type:"text"},
            {polishWord:"cytat",englishWord:"quotation ",category:"IT",type:"text"},
            {polishWord:"pulpit",englishWord:"desktop",category:"IT",type:"text"},
            {polishWord:"inerpretacja graficzna programu",englishWord:"Graphical user interface",category:"IT",type:"text"},
            {polishWord:"wskaźnik",englishWord:"pointer",category:"IT",type:"text"},
            {polishWord:"przeciągnij i upuść",englishWord:"drag and drop",category:"IT",type:"text"},
            {polishWord:"skrót",englishWord:"shortcut",category:"IT",type:"text"},
            {polishWord:"usunąć z ekranu",englishWord:"take off screen",category:"IT",type:"text"},
            {polishWord:"minimalizować",englishWord:"minimize",category:"IT",type:"text"},
            {polishWord:"ukryć",englishWord:"hide",category:"IT",type:"text"},
            {polishWord:"ukryte",englishWord:"hidden",category:"IT",type:"text"},
            {polishWord:"maksymalizować",englishWord:"maximize",category:"IT",type:"text"},
            {polishWord:"pełny ekran",englishWord:"full screen",category:"IT",type:"text"},
            {polishWord:"szerokość",englishWord:"width",category:"IT",type:"text"},
            {polishWord:"linia poleceń",englishWord:"command line",category:"IT",type:"text"},
            {polishWord:"ikony",englishWord:"icons",category:"IT",type:"text"},
            {polishWord:"ułożyć pliki",englishWord:"organize files",category:"IT",type:"text"},
            {polishWord:"wzmianka",englishWord:"mention",category:"IT",type:"text"},
            {polishWord:"wystąpić, zdarzyć wydarzyć",englishWord:"to occur",category:"IT",type:"text"},
            {polishWord:"wyszukiwarka",englishWord:"search engine",category:"IT",type:"text"},
            {polishWord:"przeglądarka",englishWord:"browser",category:"IT",type:"text"},
            {polishWord:"S.A.",englishWord:"inc",category:"IT",type:"text"},
            {polishWord:"hiperłącze",englishWord:"hyperlink",category:"IT",type:"text"},
            {polishWord:"oczekiwać",englishWord:"to expect",category:"IT",type:"text"},
            {polishWord:"Wejście",englishWord:"hit",category:"IT",type:"text"},
            {polishWord:"nawigować",englishWord:"navigate",category:"IT",type:"text"},
            {polishWord:"stworzyć",englishWord:"compose",category:"IT",type:"text"},
            {polishWord:"notatka służbowa",englishWord:"memo",category:"IT",type:"text"},
            {polishWord:"dostępny",englishWord:"available",category:"IT",type:"text"},
            {polishWord:"pojawić się",englishWord:"appear",category:"IT",type:"text"},
            {polishWord:"przewyższać się, wyróżniać się, prześcigać",englishWord:"excel",category:"IT",type:"text"},
            {polishWord:"dostęp ",englishWord:"access",category:"IT",type:"text"},
            {polishWord:"baza danych",englishWord:"database",category:"IT",type:"text"},
            {polishWord:"sortować",englishWord:"sort",category:"IT",type:"text"},
            {polishWord:"grupować",englishWord:"group by",category:"IT",type:"text"},
            {polishWord:"porządkować, układać",englishWord:"order by",category:"IT",type:"text"},
            {polishWord:"gdzie",englishWord:"where",category:"IT",type:"text"},
            {polishWord:"formuły",englishWord:"formulas",category:"IT",type:"text"},
            {polishWord:"formularz",englishWord:"form ",category:"IT",type:"text"},
            {polishWord:"arkusz roboczy, szkic",englishWord:"worksheet",category:"IT",type:"text"},
            {polishWord:"komórki",englishWord:"cells",category:"IT",type:"text"},
            {polishWord:"wykresy",englishWord:"graphs",category:"IT",type:"text"},
            {polishWord:"wykres kołowy",englishWord:"pie chart",category:"IT",type:"text"},
            {polishWord:"zapytanie",englishWord:"query",category:"IT",type:"text"},
            {polishWord:"pole",englishWord:"field",category:"IT",type:"text"},
            {polishWord:"mając",englishWord:"having",category:"IT",type:"text"},
            {polishWord:"konkatenacja",englishWord:"concat",category:"IT",type:"text"},
            {polishWord:"przyciąć",englishWord:"trim",category:"IT",type:"text"},
            {polishWord:"wykonać",englishWord:"perform",category:"IT",type:"text"},
            {polishWord:"obliczyc (komputerowo)",englishWord:"compute",category:"IT",type:"text"},
            {polishWord:"obliczyc, kalkulować ",englishWord:"calculate",category:"IT",type:"text"},
            {polishWord:"w jakim celu",englishWord:"for what purpose",category:"IT",type:"text"},
            {polishWord:"wystrój, plan, zamysł, projektowanie, wygląd",englishWord:"design",category:"IT",type:"text"},
            {polishWord:"rozwiązanie",englishWord:"solution",category:"IT",type:"text"},
            {polishWord:"wygląd",englishWord:"apparance",category:"IT",type:"text"},
            {polishWord:"funkcjonalność",englishWord:"functionality",category:"IT",type:"text"},
            {polishWord:"widoczność",englishWord:"visibility",category:"IT",type:"text"},
            {polishWord:"użyteczność",englishWord:"usability",category:"IT",type:"text"},
            {polishWord:"zawartość, treść",englishWord:"content",category:"IT",type:"text"},
            {polishWord:"elementy wizualne",englishWord:"visual elements",category:"IT",type:"text"},
            {polishWord:"kodowanie",englishWord:"coding",category:"IT",type:"text"},
            {polishWord:"dekodowanie, rozszyfrowyw.",englishWord:"decoding",category:"IT",type:"text"},
            {polishWord:"zakodowanie, zaszyfrowanie",englishWord:"encoding",category:"IT",type:"text"},
            {polishWord:"arkusze kaskadowe stylów",englishWord:"cascade style sheets",category:"IT",type:"text"},
            {polishWord:"przewodnik, instrukcja",englishWord:"guide",category:"IT",type:"text"},
            {polishWord:"luz, spowolnienie",englishWord:"slack",category:"IT",type:"text"},
            {polishWord:"z grubsza",englishWord:"roughly",category:"IT",type:"text"},
            {polishWord:"przyjęcie, rekrutacja, izba przyjęć",englishWord:"admission",category:"IT",type:"text"},
            {polishWord:"przygotowawczy, wdrożeniowy",englishWord:"preparatory",category:"IT",type:"text"},
            {polishWord:"oszacowanie",englishWord:"estimate",category:"IT",type:"text"},
            {polishWord:"tempo, krok, chód",englishWord:"pace",category:"IT",type:"text"},
            {polishWord:"pochłaniający, wciągający",englishWord:"immersive",category:"IT",type:"text"},
            {polishWord:"zachęcić, namówić",englishWord:"to encourage",category:"IT",type:"text"},
            {polishWord:"niedoceniać, bagatelizować",englishWord:"underestimate",category:"IT",type:"text"},
            {polishWord:"raczej, najlepiej (najbardziej preferowany)",englishWord:"preferably",category:"IT",type:"text"},
            {polishWord:"stały, ciągły",englishWord:"steady",category:"IT",type:"text"},
            {polishWord:"cały, całkowity",englishWord:"entire",category:"IT",type:"text"},
            {polishWord:"spójny",englishWord:"coherent",category:"IT",type:"text"},
            {polishWord:"esej, wypracowanie",englishWord:"essay",category:"IT",type:"text"},
            {polishWord:"zamierzony",englishWord:"intended",category:"IT",type:"text"},
            {polishWord:"podobny",englishWord:"similar",category:"IT",type:"text"},
            {polishWord:"płynnie, biegle",englishWord:"fluently",category:"IT",type:"text"},
            {polishWord:"kalambur, gra słów",englishWord:"quirk",category:"IT",type:"text"},
            {polishWord:"ujawnić, odkryć",englishWord:"reveal",category:"IT",type:"text"}
            ];
    
})();